name: Fedora CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:44

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf upgrade -y
          dnf install -y \
            cmake \
            make \
            qt6-qtbase-devel \
            qt6-qttools-devel \
            extra-cmake-modules \
            kf6-kcoreaddons-devel \
            kf6-ki18n-devel \
            kf6-kwidgetsaddons-devel \
            kf6-kstatusnotifieritem-devel \
            xorg-x11-server-Xvfb

      - name: Configure
        run: cmake -B ${{ github.workspace }}/build -S .

      - name: Build
        run: cmake --build ${{ github.workspace }}/build

      - name: Test visual (Xvfb)
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
          ./build/Kaffeine

      - name: Fedora CI
        working-directory: ${{ github.workspace }}/build
        run: ctest --output-on-failure